### ISSUE TITLE
Client / uploader can't connect -- having trouble with configuration

### ISSUE THREAD

**Issue by rgristroph** [rinex20/ntripcaster_docker#1]
Firstly thank you for this project !

I installed using the instructions at https://hub.docker.com/r/rinex20/ntripcaster on Ubuntu, and havea domain pointed at my IP, and everything seems to be working on the docker side of things -- I can see it in docker ps, docker port lists 2101, and I can do docker attach and see messages like this:

[30/Nov/2022:02:03:49] Kicking unknown 1 [x.x.x.x] [Unauthorized source], connected for 0 seconds
[30/Nov/2022:02:04:07] Kicking unknown 2 [x.x.x.x] [Unauthorized source], connected for 0 seconds
[30/Nov/2022:02:04:25] Kicking unknown 3 [x.x.x.x] [Unauthorized source], connected for 0 seconds
[30/Nov/2022:02:05:17] Kicking unknown 4 [x.x.x.x] [Unauthorized source], connected for 0 seconds

I think I am somehow not configuring the user / group / source correctly.

I can go to http://mydomian:2101/home, and it says "No home page template found."

If I go to http://mydomain:2101/admin , it has the Basic Auth popup but none of the users and passwords I defined in users.aut actually work.  The lines in user.aut look like:

AUS_hacker:mypassword

where AUS_hacker is the user.  In groups.aut I have the user in a group, and sourcemounts.aut just has "all:uploader,gpsclient" in it.

Is there something simple I am missing ?

What is the best way to view logs for debugging ?  Is it via docker attach ?

**Comment by datagnss** [comment]
please set "encoder_password" in ntripcaster.conf.
This "encoder_password" is for the source to upload data to caster.

**Comment by bumabacha** [comment]
hello, will you have an upgrade?
What I really miss is a VRS (virtual Reference Station), i.e. a mountpos.conf file.. (which base station is closest to you, connect there)
cannot be integrated into it NTRIP Caster 2.0.21/2.0 version ?
Best regards !

**Comment by rgristroph** [comment]
> please set "encoder_password" in ntripcaster.conf.

Thanks for the response !  I am trying that now.

**Comment by rgristroph** [comment]
Thanks so much, it turned out "encoder_password" was the issue.  I really appreciate the help !

I'm also trying to get the web interface to work, and it keeps saying "No admin page template found" but I will make a separate issue about that if I can't debug it.
